### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by sshedi**
- Some cosmetic fixes like removal of trailing spaces
- Small code improvements like using sizeof instead of strlen
- Additions in rpm spec file
- Some fixes in makefile which include
   - Packaging conf file
   - Creating target directories if doesn't exist

### CODE REVIEW

**Comment by sshedi** [comment]
@donapieppo I'm not sure on how to do the debian equivalent of changes I did in rpm spec.
Can you please assist? Feel free to add a commit to this series.

**Comment by donapieppo** [comment]
Great! Lot of work, thank you! Give me some time to look and understand it and I'll merge.

**Comment by donapieppo** [comment]
Can you give some insight on the change from

`get_static(&buffer, &buflen, strlen("x") + 1)`

to

`get_static(&buffer, &buflen, (int)sizeof("x"))`

Can it be applied also to `get_static(&buffer, &buflen, strlen(name) + 1)`?

**Comment by sshedi** [comment]
> Can you give some insight on the change from
> 
> `get_static(&buffer, &buflen, strlen("x") + 1)`
> 
> to
> 
> `get_static(&buffer, &buflen, (int)sizeof("x"))`
> 

Here we need length of string + 1 and it's a single character.
For any given string, `strlen(string) + 1 = sizeof(string)`

> Can it be applied also to `get_static(&buffer, &buflen, strlen(name) + 1)`?

We can't apply the same here, `name` is a string which can be anything and we can't decide the length at compile time.

**Pull request merged**
